package org.example.dao.db2.model;

import java.util.Date;

public class TestMergeTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.event
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.component_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Long componentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.component_name
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private String componentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.component_index
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Integer componentIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.search_page_no
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Integer searchPageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.search_page_size
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Integer searchPageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.user_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.user_type
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.session_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.client_type
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.operate_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.create_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.update_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_merge_tree.keyword
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.id
     *
     * @return the value of test_merge_tree.id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.id
     *
     * @param id the value for test_merge_tree.id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.event
     *
     * @return the value of test_merge_tree.event
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.event
     *
     * @param event the value for test_merge_tree.event
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.component_id
     *
     * @return the value of test_merge_tree.component_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Long getComponentId() {
        return componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.component_id
     *
     * @param componentId the value for test_merge_tree.component_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setComponentId(Long componentId) {
        this.componentId = componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.component_name
     *
     * @return the value of test_merge_tree.component_name
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.component_name
     *
     * @param componentName the value for test_merge_tree.component_name
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName == null ? null : componentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.component_index
     *
     * @return the value of test_merge_tree.component_index
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Integer getComponentIndex() {
        return componentIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.component_index
     *
     * @param componentIndex the value for test_merge_tree.component_index
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setComponentIndex(Integer componentIndex) {
        this.componentIndex = componentIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.search_page_no
     *
     * @return the value of test_merge_tree.search_page_no
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Integer getSearchPageNo() {
        return searchPageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.search_page_no
     *
     * @param searchPageNo the value for test_merge_tree.search_page_no
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setSearchPageNo(Integer searchPageNo) {
        this.searchPageNo = searchPageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.search_page_size
     *
     * @return the value of test_merge_tree.search_page_size
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Integer getSearchPageSize() {
        return searchPageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.search_page_size
     *
     * @param searchPageSize the value for test_merge_tree.search_page_size
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setSearchPageSize(Integer searchPageSize) {
        this.searchPageSize = searchPageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.user_id
     *
     * @return the value of test_merge_tree.user_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.user_id
     *
     * @param userId the value for test_merge_tree.user_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.user_type
     *
     * @return the value of test_merge_tree.user_type
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.user_type
     *
     * @param userType the value for test_merge_tree.user_type
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.session_id
     *
     * @return the value of test_merge_tree.session_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.session_id
     *
     * @param sessionId the value for test_merge_tree.session_id
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.client_type
     *
     * @return the value of test_merge_tree.client_type
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.client_type
     *
     * @param clientType the value for test_merge_tree.client_type
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.operate_time
     *
     * @return the value of test_merge_tree.operate_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.operate_time
     *
     * @param operateTime the value for test_merge_tree.operate_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.create_time
     *
     * @return the value of test_merge_tree.create_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.create_time
     *
     * @param createTime the value for test_merge_tree.create_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.update_time
     *
     * @return the value of test_merge_tree.update_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.update_time
     *
     * @param updateTime the value for test_merge_tree.update_time
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_merge_tree.keyword
     *
     * @return the value of test_merge_tree.keyword
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_merge_tree.keyword
     *
     * @param keyword the value for test_merge_tree.keyword
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}