package org.example.dao.db1.model;

import java.util.Date;

public class Category {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * category.id
     *
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * category.parent_id
     *
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * category.name
     *
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * category.weight
     *
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * category.create_time
     *
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column category.id
     *
     * @return the value of category.id
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column category.id
     *
     * @param id the value for category.id
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column category.parent_id
     *
     * @return the value of category.parent_id
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column category.parent_id
     *
     * @param parentId the value for category.parent_id
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column category.name
     *
     * @return the value of category.name
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column category.name
     *
     * @param name the value for category.name
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column category.weight
     *
     * @return the value of category.weight
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column category.weight
     *
     * @param weight the value for category.weight
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column category.create_time
     *
     * @return the value of category.create_time
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column category.create_time
     *
     * @param createTime the value for category.create_time
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}