package org.example.dao.model;

import java.util.Date;

public class ComponentOperation {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.ip
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.user_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.user_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Byte userType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.workspace_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Long workspaceId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.workspace_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Byte workspaceType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.component_project_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Long componentProjectId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.component_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private String componentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.component_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Byte componentType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Byte operation;

    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * component_operation.create_time
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.id
     *
     * @return the value of component_operation.id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.id
     *
     * @param id
     *            the value for component_operation.id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.ip
     *
     * @return the value of component_operation.ip
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.ip
     *
     * @param ip
     *            the value for component_operation.ip
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.user_id
     *
     * @return the value of component_operation.user_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.user_id
     *
     * @param userId
     *            the value for component_operation.user_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.user_type
     *
     * @return the value of component_operation.user_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.user_type
     *
     * @param userType
     *            the value for component_operation.user_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.workspace_id
     *
     * @return the value of component_operation.workspace_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Long getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.workspace_id
     *
     * @param workspaceId
     *            the value for component_operation.workspace_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setWorkspaceId(Long workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.workspace_type
     *
     * @return the value of component_operation.workspace_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Byte getWorkspaceType() {
        return workspaceType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.workspace_type
     *
     * @param workspaceType
     *            the value for component_operation.workspace_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setWorkspaceType(Byte workspaceType) {
        this.workspaceType = workspaceType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.component_project_id
     *
     * @return the value of component_operation.component_project_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Long getComponentProjectId() {
        return componentProjectId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.component_project_id
     *
     * @param componentProjectId
     *            the value for component_operation.component_project_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setComponentProjectId(Long componentProjectId) {
        this.componentProjectId = componentProjectId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.component_id
     *
     * @return the value of component_operation.component_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public String getComponentId() {
        return componentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.component_id
     *
     * @param componentId
     *            the value for component_operation.component_id
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setComponentId(String componentId) {
        this.componentId = componentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.component_type
     *
     * @return the value of component_operation.component_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Byte getComponentType() {
        return componentType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.component_type
     *
     * @param componentType
     *            the value for component_operation.component_type
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setComponentType(Byte componentType) {
        this.componentType = componentType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.operation
     *
     * @return the value of component_operation.operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Byte getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.operation
     *
     * @param operation
     *            the value for component_operation.operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setOperation(Byte operation) {
        this.operation = operation;
    }

    public Date getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * component_operation.create_time
     *
     * @return the value of component_operation.create_time
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * component_operation.create_time
     *
     * @param createTime
     *            the value for component_operation.create_time
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}