package org.example.dao.model;

import java.util.Date;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.user_id
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.code
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.status
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.type
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.create_time
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.update_time
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.support_suffix
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private String supportSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.logo_url
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    private String logoUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.user_id
     *
     * @return the value of shop.user_id
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.user_id
     *
     * @param userId the value for shop.user_id
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.code
     *
     * @return the value of shop.code
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.code
     *
     * @param code the value for shop.code
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.status
     *
     * @return the value of shop.status
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.status
     *
     * @param status the value for shop.status
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.type
     *
     * @return the value of shop.type
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.type
     *
     * @param type the value for shop.type
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.create_time
     *
     * @return the value of shop.create_time
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.create_time
     *
     * @param createTime the value for shop.create_time
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.update_time
     *
     * @return the value of shop.update_time
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.update_time
     *
     * @param updateTime the value for shop.update_time
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.support_suffix
     *
     * @return the value of shop.support_suffix
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public String getSupportSuffix() {
        return supportSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.support_suffix
     *
     * @param supportSuffix the value for shop.support_suffix
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setSupportSuffix(String supportSuffix) {
        this.supportSuffix = supportSuffix == null ? null : supportSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.logo_url
     *
     * @return the value of shop.logo_url
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.logo_url
     *
     * @param logoUrl the value for shop.logo_url
     *
     * @mbg.generated Fri Jul 10 16:31:26 CST 2020
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }
}