package org.example.dao.db1.mapper;

import org.example.dao.db1.model.Category;

public interface CategoryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * category
     *
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * category
     *
     * @mbg.generated Wed Jul 15 13:59:33 CST 2020
     */
    int insertSelective(Category record);
}