package org.example.dao.db1.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.example.dao.db1.model.ComponentOperation;

/**
 * @author liuwg-a
 * @date 2020/7/9 16:29
 * @description
 */
@Mapper
public interface ComponentOperationMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * component_operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * component_operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    int insert(ComponentOperation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * component_operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    int insertSelective(ComponentOperation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * component_operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    ComponentOperation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * component_operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    int updateByPrimaryKeySelective(ComponentOperation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * component_operation
     *
     * @mbggenerated Sat Jun 13 10:20:15 CST 2020
     */
    int updateByPrimaryKey(ComponentOperation record);
}
