package org.example.dao.db2.mapper;

import org.apache.ibatis.annotations.Param;
import org.example.dao.db2.model.TestMergeTree;

public interface TestMergeTreeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * test_merge_tree
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    int insert(TestMergeTree record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * test_merge_tree
     *
     * @mbg.generated Thu Jul 23 11:10:57 CST 2020
     */
    int insertSelective(TestMergeTree record);

    TestMergeTree selectById(@Param("id") Integer id);
}